name: Docker Image CI - HTML

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  |
        docker build . --file Dockerfile --tag ghcr.io/norbert-gemes/html:0.1
        docker login ghcr.io -u norbert-gemes -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/norbert-gemes/html:0.1
